sudo: false
language: python
# Travis CI matrix makes deploying one thing if all builds are
# successful hard. Instead lets just install all the Python versions on
# one container.
install:
- curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
- pyenv install 2.7.13
- pyenv install 3.0.1
- pyenv install 3.1.5
- pyenv install 3.2.6
- pyenv install 3.3.6
- pyenv install 3.4.6
- pyenv install 3.5.3
- pyenv install 3.6.1
- pyenv global 3.6.1 2.7.13 2.5.6 2.6.9 3.0.1 3.1.5 3.2.6 3.3.6 3.4.3 3.5.2
# Have to pin coverage to the same version used by tox, otherwise the
# file format changes.
- >
    pip install
    coverage==4.4.1
    python-coveralls==2.9.1
    tox==2.7.0
    virtualenv==13.1.2
script: tox
after_success: coverage
deploy:
- provider: pypi
  user: ferhai
  password:
    secure: UCQnX4ya20VyTBqLZKBJ9AR827geouSbM1BqpcrnU928nUuyx2ARIgqqaldxjwPvKbGOpMK2LOqp0qLIFGyTV4oZaUMOEHX1HC93huMyu9QBgkZFvgYy82ZYhlgsvmrXGviS3iPx2kBdtclb+bzwS1M5paPi3xR73cvIi+FTzQh35GMyswAXFuizgiH9MJZU+q1vls/G38BVk/jKX7cm0Lito07df92SBONDw3apdvyuVvSHdOPYXss2INZdMcToU6C9jopOp4xU/Nrb+0SXcV0K8keUa48467ZCh1YrGh8vHM2JLxH9jHWsSR0UEHAWwXAkNIlf57YyoCYKPQZev1MxGsxTZ6UyVWyG2zgeyB9UU7pJCj1ZYl7GRUSz9yxdpU/p4TjyCLqyyQjlHO6fnccL0RFk63gAuxOzze0kOFzHJoUBVUs3tR36cAIv3XTpPMm5M5pkCKxv7DW/uAQ9UXDyF+xCClWoilrkDEZ3DBzTIjwKpGyAJVAfYFl8WSrTALQzIXgsvEbO65BJFchgIpPDj7aOUUxk8gB6QPVJ2+yEElFlgKpW1OgJnitNcJ+ckShOoFVgdRayD6gYBITEMwwf2YyTblr1fLFemJCtFvBaIuPqoDfoYxMoDT0KbdMCWuCkZCrhmTH3Xwni4sfEu3tfyjuC3ZNOhTNpek0hmL8=
